import { createHash } from 'node:crypto'
import type { IdSource, SqlStatement } from '@durablerun/core'
import { testIdSource } from '@durablerun/core/testing'
import { MysqlStoreAdmin } from './admin.js'
import { MysqlExecutor, createOwnedMysqlPool } from './executor.js'

let fixtureSerial = 0

/**
 * MySQL catalog projection consumed by the shared schema/admin surface. It returns
 * every column of each requested table; the shared runner, not this helper, selects and
 * compares the integer contract. `information_schema` names its columns in upper case,
 * so each is aliased to the shared evidence name.
 */
export function mysqlPersistedIntegerCatalogStatements(
  tables: readonly string[],
): readonly SqlStatement[] {
  return tables.map((table) => ({
    sql: `SELECT TABLE_NAME AS table_name,
                 COLUMN_NAME AS column_name,
                 DATA_TYPE AS native_type,
                 CASE IS_NULLABLE WHEN 'YES' THEN 1 ELSE 0 END AS nullable
          FROM information_schema.columns
          WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = ?
          ORDER BY ORDINAL_POSITION`,
    args: [table],
  }))
}

export interface OpenMysqlTestDbOptions {
  /** Defaults to DURABLERUN_MYSQL_URL. */
  readonly connectionString?: string
  readonly nowMs?: number
  readonly idNamespace?: string
  /** Defaults to true. False exposes a genuinely fresh database. */
  readonly migrate?: boolean
}

/**
 * Open one test database inside an existing MySQL server. In MySQL a schema is a
 * database, so each fixture gets its own and drops it on close, through a separate
 * control connection.
 */
export async function openMysqlTestDb(options: OpenMysqlTestDbOptions = {}): Promise<{
  raw: MysqlExecutor
  admin: MysqlStoreAdmin
  ids: IdSource
  databaseName: string
  /** Holds the write lock on one task's row, from a connection of its own, until `during` settles. */
  holdTaskRowLock(taskId: string, during: () => Promise<void>): Promise<void>
  close: () => Promise<void>
}> {
  const connectionString = options.connectionString ?? process.env.DURABLERUN_MYSQL_URL
  if (!connectionString) {
    throw new Error('MySQL test fixture requires connectionString or DURABLERUN_MYSQL_URL')
  }

  const idNamespace = options.idNamespace ?? 'mysql-test'
  const databaseName = fixtureDatabaseName(idNamespace)
  const control = createOwnedMysqlPool({ uri: connectionString, connectionLimit: 1 })
  let raw: MysqlExecutor | undefined
  let closed = false

  const cleanup = async (): Promise<void> => {
    if (closed) return
    closed = true
    let firstError: unknown
    if (raw !== undefined) {
      try {
        await raw.close()
      } catch (error) {
        firstError = error
      }
    }
    try {
      // databaseName is generated by fixtureDatabaseName and contains only the
      // lowercase identifier alphabet; no caller text reaches this DDL.
      await control.query(`DROP DATABASE ${databaseName}`)
    } catch (error) {
      firstError ??= error
    }
    try {
      await control.end()
    } catch (error) {
      firstError ??= error
    }
    if (firstError !== undefined) throw firstError
  }

  const holdTaskRowLock = async (taskId: string, during: () => Promise<void>): Promise<void> => {
    const holder = await control.getConnection()
    try {
      await holder.query('START TRANSACTION')
      // databaseName contains only the lowercase identifier alphabet, as above.
      await holder.query(`SELECT task_id FROM ${databaseName}.tasks WHERE task_id = ? FOR UPDATE`, [
        taskId,
      ])
      try {
        await during()
      } finally {
        await holder.query('ROLLBACK')
      }
    } finally {
      holder.release()
    }
  }

  try {
    await control.query(
      `CREATE DATABASE ${databaseName} CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin`,
    )
    raw = MysqlExecutor.open({ uri: connectionString, database: databaseName })
    const admin = new MysqlStoreAdmin(raw)
    const ids = testIdSource(idNamespace)
    if (options.migrate !== false) await admin.migrate()
    if (options.nowMs !== undefined) await admin.setFakeNowEpochMs(options.nowMs)
    return { raw, admin, ids, databaseName, holdTaskRowLock, close: cleanup }
  } catch (error) {
    await cleanup().catch(() => undefined)
    throw error
  }
}

function fixtureDatabaseName(seed: string): string {
  const serial = ++fixtureSerial
  const digest = createHash('sha256')
    .update(`${process.pid}:${serial}:${seed}`)
    .digest('hex')
    .slice(0, 20)
  return `durablerun_${process.pid}_${serial}_${digest}`
}
