import { createHash } from 'node:crypto'
import type { IdSource, SqlStatement } from '@durablerun/core'
import { testIdSource } from '@durablerun/core/testing'
import { PostgresStoreAdmin } from './admin.js'
import { PgExecutor, createOwnedPostgresPool } from './executor.js'

let fixtureSerial = 0

/**
 * PostgreSQL catalog projection consumed by the shared schema/admin surface.
 * It deliberately returns every column for each requested table; the shared
 * runner, not this dialect helper, selects and compares the integer contract.
 */
export function postgresPersistedIntegerCatalogStatements(
  tables: readonly string[],
): readonly SqlStatement[] {
  return tables.map((table) => ({
    sql: `SELECT table_name,
                 column_name,
                 data_type AS native_type,
                 CASE is_nullable
                   WHEN 'YES' THEN CAST(1 AS BIGINT)
                   ELSE CAST(0 AS BIGINT)
                 END AS nullable
          FROM information_schema.columns
          WHERE table_schema = current_schema()
            AND table_name = ?
          ORDER BY ordinal_position`,
    args: [table],
  }))
}

export interface OpenPostgresTestDbOptions {
  /** Defaults to DURABLERUN_POSTGRES_URL. */
  readonly connectionString?: string
  readonly nowMs?: number
  readonly idNamespace?: string
  /** Defaults to true. False exposes a genuinely fresh schema. */
  readonly migrate?: boolean
}

/**
 * Open one test database namespace inside an existing PostgreSQL server.
 *
 * A private schema is materially faster than creating a whole database per
 * conformance case while retaining isolation. The data pool pins search_path
 * to that schema; cleanup first drains it and then drops exactly the generated
 * schema through a separate control pool.
 */
export async function openPostgresTestDb(options: OpenPostgresTestDbOptions = {}): Promise<{
  raw: PgExecutor
  admin: PostgresStoreAdmin
  ids: IdSource
  schemaName: string
  /** Holds the write lock on one task's row, from a connection of its own, until `during` settles. */
  holdTaskRowLock(taskId: string, during: () => Promise<void>): Promise<void>
  close: () => Promise<void>
}> {
  const connectionString = options.connectionString ?? process.env.DURABLERUN_POSTGRES_URL
  if (!connectionString) {
    throw new Error('PostgreSQL test fixture requires connectionString or DURABLERUN_POSTGRES_URL')
  }

  const idNamespace = options.idNamespace ?? 'postgres-test'
  const schemaName = fixtureSchemaName(idNamespace)
  const control = createOwnedPostgresPool({ connectionString })
  let raw: PgExecutor | undefined
  let closed = false

  const cleanup = async (): Promise<void> => {
    if (closed) return
    closed = true
    let firstError: unknown
    if (raw !== undefined) {
      try {
        await raw.close()
      } catch (error) {
        firstError = error
      }
    }
    try {
      // schemaName is generated by fixtureSchemaName and contains only the
      // lowercase identifier alphabet; no caller text reaches this DDL.
      await control.query(`DROP SCHEMA ${schemaName} CASCADE`)
    } catch (error) {
      firstError ??= error
    }
    try {
      await control.end()
    } catch (error) {
      firstError ??= error
    }
    if (firstError !== undefined) throw firstError
  }

  const holdTaskRowLock = async (taskId: string, during: () => Promise<void>): Promise<void> => {
    const holder = await control.connect()
    try {
      await holder.query('BEGIN')
      // schemaName contains only the lowercase identifier alphabet, as above.
      await holder.query(`SELECT 1 FROM ${schemaName}.tasks WHERE task_id = $1 FOR UPDATE`, [
        taskId,
      ])
      try {
        await during()
      } finally {
        await holder.query('ROLLBACK')
      }
    } finally {
      holder.release()
    }
  }

  try {
    await control.query(`CREATE SCHEMA ${schemaName}`)
    raw = PgExecutor.open({
      connectionString,
      options: `-c search_path=${schemaName}`,
    })
    const admin = new PostgresStoreAdmin(raw)
    const ids = testIdSource(idNamespace)
    if (options.migrate !== false) await admin.migrate()
    if (options.nowMs !== undefined) await admin.setFakeNowEpochMs(options.nowMs)
    return { raw, admin, ids, schemaName, holdTaskRowLock, close: cleanup }
  } catch (error) {
    await cleanup().catch(() => undefined)
    throw error
  }
}

function fixtureSchemaName(seed: string): string {
  const serial = ++fixtureSerial
  const digest = createHash('sha256')
    .update(`${process.pid}:${serial}:${seed}`)
    .digest('hex')
    .slice(0, 20)
  return `durablerun_${process.pid}_${serial}_${digest}`
}
